FROM node:16.8.0

# Update packages
RUN \ 
    apt update && \
    apt install --assume-yes mycli

# Create app directory
WORKDIR /app

# Copy configs to WORKDIR
COPY package*.json ./
COPY tsconfig.json ./

# Copy source code to /app/src folder
COPY src /app/src

# check files list
RUN ls -a

# Install dependencies
RUN \
    npm install -g typescript && \
    npm install -g ts-node && \
    npm install && \
# Build a /dist folder
    npm run build

# Expose container port
EXPOSE 8080

CMD ["npm", "run", "watch"]