version: "3.3"

services:
    vscode:
        build:
            context: ./
            dockerfile: ./Dockerfile
        command: /bin/bash -c "while sleep 1000; do :; done"
        ports:
            - "3333:3333"
        container_name: backendProject
        working_dir: /server
        networks:
            - app-network
        volumes:
            # Nous allons préciser le dossier local
            - .:/server:cached

    dbms:
        image: mariadb
        restart: always
        ports:
            - "3306:3306"
        env_file:
            - .env
        command: ["--character-set-server=utf8mb4", "--collation-server=utf8mb4_unicode_ci"]
        volumes:
            - ./dbms/dbms-data:/var/lib/mysql
            - ./dbms/mariadb.cnf:/etc/mysql/mariadb.cnf
            # Pointer vers un dossier qui aura des scripts d'initialisation de notre base
            - ./dbms/dev-initdb.d:/docker-entrypoint-initdb.d
            # Ajouter le DDL qui va tourner en dernier
            - ./dbms/ddl/ddl.sql:/docker-entrypoint-initdb.d/999-ddl.sql
        networks:
            - app-network

networks:
    app-network:
        driver: bridge
